### ISSUE TITLE
unused environment variable?

### ISSUE THREAD

**Issue by klaw772** [JWBlash/hillbot#1]
where is 'booplesnoots' being used in cedar rapids

https://github.com/JWBlash/hillbot/blob/9a17526e5425845f1c4ff0d088d66c9de1eae186/hillbot.py#L9

**Comment by JWBlash** [comment]
This is actually a good question. I think I left that in there while writing things but I'm not sure if it's used literally at all. I need to experiment tomorrow :o

**Comment by JWBlash** [comment]
Fixed!
